# Shop Origin 一键启动配置
# 包含前端管理系统、后端API、数据库和缓存服务

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: shop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "cool"
      MYSQL_USER: "cool"
      MYSQL_PASSWORD: "123456"
      TZ: Asia/Shanghai
    networks:
      - shop-network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./shop-api-origin/src/main/resources/sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: shop-redis
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    networks:
      - shop-network
    ports:
      - "16379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  # 数据库管理工具 (可选)
  adminer:
    image: adminer:latest
    container_name: shop-adminer
    networks:
      - shop-network
    ports:
      - "18080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: pepa-linha
    depends_on:
      - mysql
    restart: unless-stopped

networks:
  shop-network:
    driver: bridge
    name: shop-network

volumes:
  mysql-data:
    driver: local
    name: shop-mysql-data
  redis-data:
    driver: local
    name: shop-redis-data
  api-uploads:
    driver: local
    name: shop-api-uploads
